name: cryosiam_vis
channels:
  - conda-forge
dependencies:
  - plotly<=5.24.1
  - dash==2.14.2
  - pandas
  - pyyaml
  - mrcfile
  - h5py
  - napari
  - pyqt
  - starfile
  - pip
  - pip:
      - dash-slicer==0.3.1
      - dash_bootstrap_components==1.7.1
